name: Build Flutter APK

on:
  push:
    branches:
      - master  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'  # Change this to the Flutter version you are using
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk